### ISSUE TITLE
The game does not start while fix is installed

### ISSUE THREAD

**Issue by Mustrumion** [ayles/NieRMouseFix#2]
![error message screen](https://user-images.githubusercontent.com/12587249/48984951-7d58cb80-f102-11e8-84d1-82a82abf0263.PNG)
When I start the game with Steam it silently fails. Running it through .exe produces the error message I attached. No logs were created in the game directory.

I highly appreciate your work. If you still don't own a copy of the game I can gift you it on Steam. (No strings attached, you don't need to fix anything. I just admire that you worked on this and shared it.)

**Comment by ayles** [comment]
@Mustrumion
Sorry, was busy.

> When I start the game with Steam it silently fails. Running it through .exe produces the error message I attached. No logs were created in the game directory.

I apologize for that. I have already heard about a similar problem with the official copy of the game and the latest FAR.

> If you still don't own a copy of the game I can gift you it on Steam.

Yes, I do not have it yet. You can gift it if you want, I will be very grateful.

Anyway, I'll see what I can do.

Can you give me more details about your case? 
Is far installed? Or just game as is?
(Or you can email me - <selya.main@gmail.com>).

**Comment by SaMaili** [comment]
I have the same issue. Is it fixed yet?

**Comment by ayles** [comment]
> I have the same issue. Is it fixed yet?

Hi! Idk, that was a long time ago and I mostly fixed this for myself to finally finish the game. I believe there is alive nier modding community somewhere on discord, you can ask there. I sadly have no spare time nowadays to look into that(
